# Generated by Django 4.2.1 on 2023-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
        ('main', '0007_remove_main_product_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='product',
            field=models.ManyToManyField(through='main.OrderItem', to='products.product'),
        ),
    ]
