# Generated by Django 4.2.1 on 2023-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_main_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='product',
        ),
        migrations.AddField(
            model_name='main',
            name='with_delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
    ]
